### ISSUE TITLE
ERROR: Cannot install -r python_requirements.txt 

### ISSUE THREAD

**Issue by leonheess** [AASHISHAG/deepspeech-german#43] opened 2021-05-25 09:57 UTC
While installing when using `pip3 install -r python_requirements.txt` I get:

```
ERROR: Cannot install -r python_requirements.txt (line 12), -r python_requirements.txt (line 20), -r python_requirements.txt (line 25), -r python_requirements.txt (line 26), -r python_requirements.txt (line 31), -r python_requirements.txt (line 34), -r python_requirements.txt (line 4), -r python_requirements.txt (line 45), -r python_requirements.txt (line 47), -r python_requirements.txt (line 48), -r python_requirements.txt (line 54), -r python_requirements.txt (line 56) and numpy==1.18.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.18.1
    audiomate 6.0.0 depends on numpy==1.18.1
    ds-ctcdecoder 0.9.3 depends on numpy>=1.14.5
    h5py 2.10.0 depends on numpy>=1.7
    keras-preprocessing 1.1.2 depends on numpy>=1.9.1
    librosa 0.7.2 depends on numpy>=1.15.0
    numba 0.49.1 depends on numpy>=1.15
    opt-einsum 3.3.0 depends on numpy>=1.7
    resampy 0.2.2 depends on numpy>=1.10
    scikit-learn 0.24.0 depends on numpy>=1.13.3
    scipy 1.4.1 depends on numpy>=1.13.3
    tensorboard 2.4.0 depends on numpy>=1.12.0
    tensorflow 2.4.0 depends on numpy~=1.19.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by AASHISHAG** [comment] 2021-05-25 19:29
Hi @leonheess, I would be glad if you could please submit a pull request to fix the dependency issues. :)

**Comment by leonheess** [comment] 2021-06-03 17:58
> Hi @leonheess, I would be glad if you could please submit a pull request to fix the dependency issues. :)

I tried quite a bit but since audiomate requires 1.18.1 and tensorflow wants 1.19.2, I wasn't able to resolve the issue. Can you give me a hint?

**Comment by michelleespranita** [comment] 2021-06-04 11:17
You could try to downgrade your pip version to 20.2.3, which allows you to install packages despite dependency conflicts.

**Comment by moejoe95** [comment] 2021-06-15 08:37
a solution could be to pass the `--no-dependency` flag:
```
pip3 install -r python_requirements.txt --no-dependencies

```

**Comment by leonheess** [comment] 2021-06-16 19:38
> a solution could be to pass the `--no-dependency` flag:
> 
> ```
> pip3 install -r python_requirements.txt --no-dependencies
> ```

I tried that but then I'm getting the following when trying to download stuff:
```

s.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
/mnt/c/Users/MIXT4PE/Desktop/deepspeech-german/python-environments/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
Traceback (most recent call last):
  File "pre-processing/download_speech_corpus.py", line 6, in <module>
    import audiomate.corpus.io
  File "/mnt/c/Users/MIXT4PE/Desktop/deepspeech-german/python-environments/lib/python3.7/site-packages/audiomate/corpus/io/__init__.py", line 7, in <module>
    from .downloader import ArchiveDownloader
  File "/mnt/c/Users/MIXT4PE/Desktop/deepspeech-german/python-environments/lib/python3.7/site-packages/audiomate/corpus/io/downloader.py", line 7, in <module>
    from audiomate.utils import download
  File "/mnt/c/Users/MIXT4PE/Desktop/deepspeech-german/python-environments/lib/python3.7/site-packages/audiomate/utils/download.py", line 11, in <module>
    from pget.down import Downloader
  File "/mnt/c/Users/MIXT4PE/Desktop/deepspeech-german/python-environments/lib/python3.7/site-packages/pget/__init__.py", line 1, in <module>
    from down import Downloader
ModuleNotFoundError: No module named 'down'
```

**Comment by AASHISHAG** [comment] 2021-09-15 18:16
I think the issue is resolved. Closing the ticket.

**Closed by AASHISHAG** 2021-09-15 18:16 UTC
