### ISSUE TITLE
Trying to train the german model for DS 0.4.1

### ISSUE THREAD

**Issue by cli0** [AASHISHAG/deepspeech-german#5] opened 2019-12-06 13:18 UTC
Hi there,

Your german model is an excellent model and I want to use it for some research I am doing (your work will be appropriately cited :) ).

I need to train your german model for DS 0.4.1 (unfortunately I cannot use newer versions) and I am hitting an issue when it comes to bazel builds.

```
(deepspeech-german) clio@Trantor:~/Desktop/deepspeech-german/tensorflow$ bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
INFO: Analysed 2 targets (0 packages loaded).
INFO: Found 2 targets...
ERROR: /home/clio/Desktop/deepspeech-german/tensorflow/native_client/BUILD:126:1: C++ compilation of rule '//native_client:generate_trie' failed (Exit 1)
native_client/ctcdecode/swigwrapper_wrap.cpp:174:11: fatal error: Python.h: No such file or directory
 # include <Python.h>
           ^~~~~~~~~~
compilation terminated.
INFO: Elapsed time: 0.993s, Critical Path: 0.71s
INFO: 4 processes: 4 local.
FAILED: Build did NOT complete successfully
```

I followed your instructions and adapted everything tf r1.12 and bazel 0.15.0 (necessary versions for DS 0.4.1) but something about the git file disrupts the building.
I checked the tf versions

```
(deepspeech-german) clio@Trantor:~/Desktop/deepspeech-german$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

v1.12.0-0-ga6d8ffae09 1.12.0
```
and there is some semantic incompatibility although they point to the same version. Did you ever encounter a problem like this?

**Comment by AASHISHAG** [comment] 2019-12-06 14:08
@cli0 Finding the right Tensorflow and Bazel version is the tricky part while setting up DeepSpeech. I didn't use the v0.4.0 before and therefore not sure if I encountered this error with v0.5.0.

I had a look at the Dockerfile for v0.4.0. The Mozilla team had used `TensorFlow r1.12 ` and `Bazel 0.15.2`. You may also try using v0.15.2. If this doesn't work, the trick is to try experimenting with different Bazel versions.

**Comment by cli0** [comment] 2019-12-06 15:24
Thank you for the heads up. I had the wrong Bazel version apparently. I successfully ran bazel build but when I run the trie building command I get that generate_trie does not exist

```
(deepspeech-german) clio@Trantor:~/Desktop/language-dependency-of-adv-ex$ ./DeepSpeech/native_client/generate_trie deepspeech-german/data/alphabet.txt ../arpa/lm.binary ../arpa/trie
bash: ./DeepSpeech/native_client/generate_trie: No such file or directory
```

However I do have a `generate_trie.cpp` file in my folder, though uncompiled. Bazel did not throw me any errors though. Is this a Bazel error or is the compiled file somewhere else?

**Comment by AASHISHAG** [comment] 2019-12-06 15:30
I don't remember it correctly. But it definitely has to do with either Tensorflow or Bazel.

**Comment by tarnh** [comment] 2019-12-08 15:05
> [..] DS 0.4.1 (unfortunately I cannot use newer versions)
Why are you not using your private PC? Are you a "Uniknecht"?

**Comment by cli0** [comment] 2019-12-13 14:14
@tarnh I don't know what "Uniknecht" means. I am using 0.4.1 because I need to use some scripts that were specifically written for 0.4.1. Retraining the model is less of a hassle than re-writing those scripts.

@AASHISHAG  Training now works fine. One last question: in order to get the best possible results according to your paper, should I apply the hyperparameters in the paper Table 2 or the ones you have specified at train.sh? And should the batch size for all sets (test/dev/train) be 24 ?

**Comment by zesch** [comment] 2019-12-13 16:04
We always used batch size 24. I would go with the hyperparameters from the paper, but although results seem to be relatively stable wrt. to parameter choice, it definitely also depend a bit on the specific dataset.

**Comment by cli0** [comment] 2019-12-19 12:01
Guys, did you ever encounter an error like this:

```
E ../checkpoint/model.ckpt-10051.data-00000-of-00001.tempstate13871076945433806239; No space left on device                                                                                                        
E        [[node save/SaveV2 (defined at ./DeepSpeech.py:484)  = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/re
plica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, b1, b1/Adam, b1/Adam_1, b2, b2/Adam, b2/Adam_1, b3, b3/Adam, b3/Adam_1, b5, b5/Adam, b5/Adam_1, b6, b6/A
dam, b6/Adam_1, beta1_power, beta2_power, global_step, h1, h1/Adam, h1/Adam_1, h2, h2/Adam, h2/Adam_1, h3, h3/Adam, h3/Adam_1, h5, h5/Adam, h5/Adam_1, h6, h6/Adam, h6/Adam_1, lstm_fused_cell/bias, lstm_fused_cel
l/bias/Adam, lstm_fused_cell/bias/Adam_1, lstm_fused_cell/kernel, lstm_fused_cell/kernel/Adam, lstm_fused_cell/kernel/Adam_1)]]                                                                                    
E Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.     
```
It happens here:

```
E   File "./DeepSpeech.py", line 484, in train                                                                                                                                                                     
E     saver = tf.train.Saver(max_to_keep=FLAGS.max_to_keep) 
```
Error stack:

```
  File "./DeepSpeech.py", line 484, in train
    saver = tf.train.Saver(max_to_keep=FLAGS.max_to_keep)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 792, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 284, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 202, in save_op
    tensors)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1690, in save_v2
    shape_and_slices=shape_and_slices, tensors=tensors, name=name)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/clio/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): ../checkpoint/model.ckpt-10051.data-00000-of-00001.tempstate13871076945433806239; No space left on device
         [[node save/SaveV2 (defined at ./DeepSpeech.py:484)  = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/re
plica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, b1, b1/Adam, b1/Adam_1, b2, b2/Adam, b2/Adam_1, b3, b3/Adam, b3/Adam_1, b5, b5/Adam, b5/Adam_1, b6, b6/A
dam, b6/Adam_1, beta1_power, beta2_power, global_step, h1, h1/Adam, h1/Adam_1, h2, h2/Adam, h2/Adam_1, h3, h3/Adam, h3/Adam_1, h5, h5/Adam, h5/Adam_1, h6, h6/Adam, h6/Adam_1, lstm_fused_cell/bias, lstm_fused_cel
l/bias/Adam, lstm_fused_cell/bias/Adam_1, lstm_fused_cell/kernel, lstm_fused_cell/kernel/Adam, lstm_fused_cell/kernel/Adam_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```

I have set to only save 1 checkpoint and I am not running out of storage space. This happens around Epoch 8.

**Comment by AASHISHAG** [comment] 2019-12-19 13:01
No, we didn't face it before. But it seems you are running out of GPU memory.

You can refer below links:
https://discourse.mozilla.org/t/unexpected-resourceexhaustederror/28844/5
https://github.com/mozilla/DeepSpeech/issues/1386

**Comment by cli0** [comment] 2020-02-06 16:22
Hi there. I have one more question in regards to the training process. Did you make use of DeepSpeech's early stopping functionality when training? And if yes, what did you set the validation_step value as?

**Comment by AASHISHAG** [comment] 2020-02-09 10:50
@cli0 : Yes, we used early stopping functionality and didn't set any value for validation_step. We used only the following flags mentioned in [train_model.sh](https://github.com/AASHISHAG/deepspeech-german/blob/master/train_model.sh)

I am not sure about v0.4.1 and before. But this flag `validation_step` is not available in new DeepSpeech releases. Refer here: [flags.py](https://github.com/mozilla/DeepSpeech/blob/master/util/flags.py)

**Comment by cli0** [comment] 2020-02-18 11:11
Interesting. If I enable early stopping, validation sends the signal to stop by epoch 16. Do you perhaps remember a ballpark estimate of how many epochs you needed to train your model?

**Comment by AASHISHAG** [comment] 2020-02-23 23:23
@cli0 : I don't have an exact number, but it should be no more than 25.

**Comment by cli0** [comment] 2020-02-25 15:29
Thanks for the heads up. I have one more question, when I generate the csv for test/train/dev files according to your script, I can't see the umlaut Buchstaben like ä,ö,ü in the csv transcription. I dont think this is normal here. And I did run the script to UTF before running the extraction.

**Comment by AASHISHAG** [comment] 2020-03-07 17:06
Kindly verify the steps again. No such issue is reported by other users.

Note: UTF-8 is only for Voxforge dataset.

**Comment by mfmotta** [comment] 2020-04-03 12:30
> Thank you for the heads up. I had the wrong Bazel version apparently. I successfully ran bazel build but when I run the trie building command I get that generate_trie does not exist
> 
> ```
> (deepspeech-german) clio@Trantor:~/Desktop/project$ ./DeepSpeech/native_client/generate_trie deepspeech-german/data/alphabet.txt ../arpa/lm.binary ../arpa/trie
> bash: ./DeepSpeech/native_client/generate_trie: No such file or directory
> ```
> 
> However I do have a `generate_trie.cpp` file in my folder, though uncompiled. Bazel did not throw me any errors though. Is this a Bazel error or is the compiled file somewhere else?

@cli0 Hi! I'm having the same issues described above. I also have a generate_trie.cpp in /native_client. 

I was finally able to build bazel successfully after changing versions of tf, bazel and DeepSpeech to 1.12, 0.152, and v0.4.0 with 
`bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie`

You seem to have solved this problem. Could you please point out the solution?

**Comment by AASHISHAG** [comment] 2020-08-26 21:37
@cli0 : I hope the issue is resolved. Hence, closing the issue.

**Closed by AASHISHAG** 2020-08-26 21:37 UTC
