### ISSUE TITLE
On installing pip3 Not Found for url: https://pypi.org/simple/ds-ctcdecoder/

### ISSUE THREAD

**Issue by ClNeum** [AASHISHAG/deepspeech-german#16] opened 2020-05-23 09:17 UTC
I tried to install deepspeech-german on Debian stretch and get:
On installing 
pip3 install -r python_requirements.txt
I get
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/ds-ctcdecoder/

URL https://pypi.org/simple/ds-ctcdecoder/   -> 404
What now?

**Comment by TheLexoPlexx** [comment] 2020-05-23 13:26
You get this error if you do not create a virtual environment as stated in the beginning of the ReadMe.

**Comment by ClNeum** [comment] 2020-05-24 13:58
Am Samstag, 23. Mai 2020, 06:26:19 CEST schrieb Alex:
> You get this error if you do not create a virtual environment as stated in
> the beginning of the ReadMe.
> 
*claudia@Mediondebn*:*~*$ python3 -m venv deepspeech-german 
*claudia@Mediondebn*:*~*$ source deepspeech-german/bin/activate 
*claudia@Mediondebn*:*~*$ cd deepspeech-german/ 
*claudia@Mediondebn*:*~/deepspeech-german*$ pip3 install -r python_requirements.txt 
Exception:                                                                                                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                                                              
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/
basecommand.py", line 215, in main                                                                                                                                                                      
   status = self.run(options, args)                                                                                                                                                                                                                                            
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/commands/
install.py", line 353, in run                                                                                                                                                                  
   wb.build(autobuilding=True)                                                                                                                                                                                                                                                 
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/wheel.py", line 
749, in build                                                                                                                                                                           
   self.requirement_set.prepare_files(self.finder)                                                                                                                                                                                                                             
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/req/req_set.py", 
line 380, in prepare_files                                                                                                                                                             
   ignore_dependencies=self.ignore_dependencies))                                                                                                                                                                                                                              
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/req/req_set.py", 
line 554, in _prepare_file                                                                                                                                                             
   require_hashes                                                                                                                                                                                                                                                              
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/req/
req_install.py", line 278, in populate_link                                                                                                                                                         
   self.link = finder.find_requirement(self, upgrade)                                                                                                                                                                                                                          
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/index.py", line 
465, in find_requirement                                                                                                                                                                
   all_candidates = self.find_all_candidates(req.name)                                                                                                                                                                                                                         
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/index.py", line 
423, in find_all_candidates                                                                                                                                                             
   for page in self._get_pages(url_locations, project_name):                                                                                                                                                                                                                   
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/index.py", line 
568, in _get_pages                                                                                                                                                                      
   page = self._get_page(location)                                                                                                                                                                                                                                             
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/index.py", line 
683, in _get_page                                                                                                                                                                       
   return HTMLPage.get_page(link, session=self.session)                                                                                                                                                                                                                        
 File "/home/claudia/deepspeech-german/lib/python3.5/site-packages/pip/index.py", line 
795, in get_page                                                                                                                                                                        
   resp.raise_for_status()                                                                                                                                                                                                                                                     
 File "/home/claudia/deepspeech-german/share/python-wheels/requests-2.12.4-py2.py3-
none-any.whl/requests/models.py", line 893, in raise_for_status                                                                                                                             
   raise HTTPError(http_error_msg, response=self)                                                                                                                                                                                                                              
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/
ds-ctcdecoder/                          

???

Best regards

Claudia

**Comment by AASHISHAG** [comment] 2020-05-25 21:55
@ClNeum : I think we can ignore this dependency. Could you please ignore this error and continue with other steps and report and in case you face any other issue.

**Comment by ClNeum** [comment] 2020-05-26 08:30
Hi all,

I commented 

#ds-ctcdecoder==0.5.0a7


Now I get:

pip3 install -r python_requirements.txt                                                                                                                                                                             
 Cache entry deserialization failed, entry ignored 
 Ignoring singledispatch: markers 'python_version < "3.4"' don't match your environment 
 Cache entry deserialization failed, entry ignored 
 Failed building wheel for absl-py 
 Failed building wheel for audioread 
 Failed building wheel for bs4 
 Failed building wheel for docopt 
 Failed building wheel for gast 
 Failed building wheel for intervaltree 
 Failed building wheel for librosa 
 Failed building wheel for networkx 
 Failed building wheel for nltk 
 Failed building wheel for pycparser 
 Failed building wheel for python-speech-features 
 Failed building wheel for resampy 
 Failed building wheel for termcolor 


CU

Claudia


Am Montag, 25. Mai 2020, 14:55:33 CEST schrieb Aashish Agarwal:

**Comment by AASHISHAG** [comment] 2020-05-28 23:13
As a workaround (docker), please follow:

I will soon update the ReadMe. A PR is always welcomed. :)

```
git clone https://github.com/mozilla/DeepSpeech.git
cd DeepSpeech/
git checkout v0.6.0
docker build -t deepspeech_v0.6.0 .
docker ps
docker images
docker run -d -it --name deepspeech_v0.6.0 --mount  type=bind,source="$(pwd)",target=/root deepspeech_v0.6.0
docker exec -it deepspeech_v0.6.0 /bin/bash

pip3 install audiomate==3.0.0
pip3 install num2words
```

**Comment by AASHISHAG** [comment] 2020-08-26 21:38
I hope the issue is resolved. Hence, closing the issue.

**Closed by AASHISHAG** 2020-08-26 21:38 UTC
